# Generated by Django 2.1.8 on 2019-11-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_auto_20191104_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycar',
            name='goods_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
