# Generated by Django 2.1.8 on 2019-10-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quser',
        ),
    ]
