# Generated by Django 2.1.8 on 2019-10-29 09:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0002_delete_quser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('number', models.IntegerField()),
                ('production', models.DateTimeField()),
                ('safe_date', models.CharField(max_length=32)),
                ('picture', models.ImageField(default='shop/img/tao.jpg', upload_to='shop/img')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
