# Generated by Django 2.1.8 on 2019-11-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0003_goodsaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QUser.Quser'),
        ),
    ]
