# Generated by Django 2.1.8 on 2019-11-05 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0004_auto_20191105_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsaddress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QUser.Quser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsaddress',
            name='address',
            field=models.TextField(),
        ),
    ]
